### ISSUE TITLE
Avoid Cookie

### ISSUE THREAD

**Issue by ix-xerri** [zemirco/csrf-express-angular#1]
You can avoid the cookie and set it as a header. Just save it in memory and then send it via the headers.

**Comment by darethas** [comment]
I was going to ask this question on his post, but could not get disqus to load.

So, my question was, is there any advantage your technique has over just setting the default headers with angular cookie service?

i.e: something like  $http.defaults.headers.post['X-CSRFToken'] = $cookies['csrftoken'];

**Comment by zemirco** [comment]
All roads lead to rome!

It doesn't matter if you make your changes on the server or on the client.
